// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: '<span class="valid-icon glyphicon glyphicon-ok form-control-feedback"></span>',
      replace: true
    };
  };

}).call(this);

//# sourceMappingURL=ValidIcon.map
