// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(url, obj) {
    var name, regx, _i, _len;
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      name = obj[_i];
      regx = new RegExp(":" + name);
      url = url.replace(regx, obj[name]);
    }
    return url;
  };

}).call(this);

//# sourceMappingURL=FormatStringURL.map
