// Generated by CoffeeScript 1.7.1
(function() {
  var formatStringURL;

  formatStringURL = require("./FormatStringURL.coffee");

  module.exports = function(url, mapData, scope) {
    var obj;
    obj = {};
    if (typeof mapData !== "undefined") {
      obj = scope.$eval(mapData);
    }
    return formatStringURL(url, obj);
  };

}).call(this);

//# sourceMappingURL=MapDataToURL.map
