// Generated by CoffeeScript 1.7.1
(function() {
  var formatStringURL;

  formatStringURL = function(url, obj) {
    var name, regx, _i, _len;
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      name = obj[_i];
      regx = new RegExp(":" + name);
      url = url.replace(regx, obj[name]);
    }
    return url;
  };

  module.exports = function(url, mapData, scope) {
    var obj;
    obj = {};
    if (typeof mapData !== "undefined") {
      obj = scope.$eval(mapData);
    }
    return formatStringURL(url, obj);
  };

}).call(this);

//# sourceMappingURL=MapDataToURL.map
