// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  require("angular/angular");

  app = angular.module('PolyForm', []);

  module.exports = app;

}).call(this);

//# sourceMappingURL=main.map
