// Generated by CoffeeScript 1.7.1
(function() {
  global.jQuery = require("jquery");

  require("angular/angular");

  require("../js/select2");

  module.exports = angular.module('PolyForm', ['ui.select2']).directive("formTabs", require("./directives/FormTabs.coffee")).directive("formTab", require("./directives/FormTab.coffee"));

}).call(this);

//# sourceMappingURL=main.map
