// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: require('./loader-icon.jade'),
      replace: true
    };
  };

}).call(this);

//# sourceMappingURL=LoaderIcon.map
