// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: '<span class="input-group-addon"ng-transclude></span>',
      replace: true
    };
  };

}).call(this);

//# sourceMappingURL=InputGroupAddon.map
