// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: require('./date-input.jade'),
      replace: true,
      link: function(scope, element, attrs) {
        var rangeInputs, t;
        rangeInputs = null;
        if (attrs.bindInputs) {
          t = attrs.bindInputs.split(",");
          if (t.length > 0) {
            rangeInputs = [];
            angular.forEach(t, function(value) {
              return rangeInputs.push($(value));
            });
          }
        }
        return element.datepicker({
          multidate: (attrs.multidate ? attrs.multidate === "true" : false),
          forceParse: (attrs.forceParse ? attrs.forceParse === "true" : true),
          clearBtn: (attrs.clearBtn ? attrs.clearBtn === "true" : false),
          todayHighlight: (attrs.todayHighlight ? attrs.todayHighlight === "true" : true),
          autoclose: (attrs.autoclose ? attrs.autoclose === "true" : true),
          multidateSeparator: attrs.multidateSeparator || ",",
          format: attrs.format || 'dd/mm/yyyy',
          language: attrs.language || "el",
          inputs: rangeInputs
        });
      }
    };
  };

}).call(this);

//# sourceMappingURL=DateInput.map
