// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: '<div class="input-group date"> <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span> <div ng-transclude></div> </div>',
      replace: true,
      link: function(scope, element, attrs) {
        var rangeInputs, t;
        rangeInputs = null;
        if (attrs.bindInputs) {
          t = attrs.bindInputs.split(",");
          if (t.length > 0) {
            rangeInputs = [];
            angular.forEach(t, function(value) {
              return rangeInputs.push($(value));
            });
          }
        }
        return element.datepicker({
          multidate: typeof attrs.multidate === "function" ? attrs.multidate(attrs.multidate === {
            "true": false
          }) : void 0,
          forceParse: typeof attrs.forceParse === "function" ? attrs.forceParse(attrs.forceParse === {
            "true": true
          }) : void 0,
          clearBtn: typeof attrs.clearBtn === "function" ? attrs.clearBtn(attrs.clearBtn === {
            "true": false
          }) : void 0,
          todayHighlight: typeof attrs.todayHighlight === "function" ? attrs.todayHighlight(attrs.todayHighlight === {
            "true": true
          }) : void 0,
          autoclose: typeof attrs.autoclose === "function" ? attrs.autoclose(attrs.autoclose === {
            "true": true
          }) : void 0,
          multidateSeparator: attrs.multidateSeparator || ",",
          format: attrs.format || 'dd/mm/yyyy',
          language: attrs.language || "el",
          inputs: rangeInputs
        });
      }
    };
  };

}).call(this);

//# sourceMappingURL=DateInput.map
