// Generated by CoffeeScript 1.7.1
(function() {
  var formElements;

  formElements = require("../utils/FormElements.coffee");

  module.exports = function() {
    return {
      restrict: 'A',
      require: ['^form', '?^formTab'],
      scope: {
        isUniqueQuietMillis: '@',
        isUniqueMapData: '@'
      },
      link: function(scope, elm, attrs, ctrls) {
        var controlElements, controls, form, formTab, update;
        form = ctrls[0];
        formTab = ctrls[1];
        controlElements = elm.find(formElements);
        controls = [];
        if ((formTab != null) && (formTab.scope.disabled != null)) {
          formTab.scope.$watch("disabled", function(value) {
            return update(scope.$eval(attrs.ngShow));
          });
        }
        if ((attrs.ngShow != null)) {
          scope.$watch(attrs.ngShow, function(value) {
            return update(value);
          });
        }
        if ((attrs.ngHide != null)) {
          scope.$watch(attrs.ngHide, function(value) {
            return update(!value);
          });
        }
        return update = function(value) {
          return controlElements.each(function(controlElement) {
            var control, element;
            element = $(this);
            control = form[element.attr("name")];
            if (!(control != null)) {
              control = controlElement;
            } else {
              controls.push(control);
            }
            if (!(control != null)) {
              return;
            }
            if (value === true) {
              $(element).removeAttr('disabled');
              form.$addControl(control);
              return angular.forEach(control.$error, function(validity, validationToken) {
                return form.$setValidity(validationToken, !validity, control);
              });
            } else {
              $(element).attr('disabled', 'disabled');
              return form.$removeControl(control);
            }
          });
        };
      }
    };
  };

}).call(this);

//# sourceMappingURL=DisableValidationWhenHidden.map
