// Generated by CoffeeScript 1.7.1
(function() {
  var $, formElements, _;

  $ = require("jquery");

  formElements = require("../utils/FormElements.coffee");

  _ = require("lodash");

  module.exports = function() {
    return {
      restrict: 'A',
      require: ['^form', '?^formTab'],
      scope: {
        isUniqueQuietMillis: '@',
        isUniqueMapData: '@'
      },
      link: function(scope, elm, attrs, ctrls) {
        var controlElements, controls, form, formTab, update, _ref;
        form = ctrls[0];
        formTab = ctrls[1];
        controlElements = elm.find(formElements);
        controls = [];
        if (((formTab != null ? (_ref = formTab.scope) != null ? _ref.disabled : void 0 : void 0) != null)) {
          formTab.scope.$watch("disabled", function(value) {
            return update(scope.$eval(attrs.ngShow));
          });
        }
        if ((attrs.ngShow != null)) {
          scope.$parent.$watch(attrs.ngShow, function(value) {
            return update(value);
          });
        }
        if ((attrs.ngHide != null)) {
          scope.$parent.$watch(attrs.ngHide, function(value) {
            return update(!value);
          });
        }
        if ((attrs.ngDisabled != null)) {
          scope.$parent.$watch(attrs.ngDisabled, function(value) {
            return update(!value);
          });
        }
        return update = function(value) {
          controlElements.each(function(index) {
            var control, element;
            element = $(this);
            control = form[element.attr("name")];
            if (!_.contains(controls, control)) {
              controls.push(control);
            }
            if (value) {
              return $(element).removeAttr('disabled');
            } else {
              return $(element).attr('disabled', 'disabled');
            }
          });
          return _.forEach(controls, function(control) {
            if (!(control != null)) {
              return;
            }
            if (value) {
              form.$addControl(control);
              return angular.forEach(control.$error, function(validity, validationToken) {
                return form.$setValidity(validationToken, !validity, control);
              });
            } else {
              return form.$removeControl(control);
            }
          });
        };
      }
    };
  };

}).call(this);

//# sourceMappingURL=DisableValidationWhenHidden.map
