// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return {
      restrict: 'E',
      transclude: true,
      template: '<div class="input-group" ng-transclude></div>',
      replace: true
    };
  };

}).call(this);

//# sourceMappingURL=InputGroup.map
