// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = require("jquery");

  module.exports = function() {
    return {
      restrict: 'A',
      require: '?ngModel',
      link: function(scope, elm, attrs, ngModel) {
        var validatorFn;
        scope.$evalAsync(function() {
          return $(attrs.isEqual).bind("keyup input blur", function() {
            validatorFn(ngModel.$modelValue);
            return scope.$digest();
          });
        });
        validatorFn = function(viewValue) {
          var itemToObserveValue, value;
          itemToObserveValue = $(attrs.isEqual);
          value = (itemToObserveValue.length === 0 ? "" : itemToObserveValue.val());
          if (viewValue === value) {
            ngModel.$setValidity('isEqual', true);
          } else {
            ngModel.$setValidity('isEqual', false);
          }
          return viewValue;
        };
        return ngModel.$parsers.unshift(validatorFn);
      }
    };
  };

}).call(this);

//# sourceMappingURL=IsEqual.map
